# Site Settings
title: SLSR API
email: webmaster@slsr.org
description: >
  API of the Second Life Shinto shrine register (SLSR).
baseurl: ""
url: "https://api.slsr.org"

# Handling Reading
include: ['_endpoints']
exclude: ['CNAME']

# Build Settings
kramdown:
  input: GFM
